---
- name: Generate arista overlay configs
  hosts: leaf
  gather_facts: false
  
  roles:
  - cvp_generate

- name: Generate arista overlay configs
  hosts: CVP
  gather_facts: false

  roles:
  - cvp_deploy