---
# tasks file for cvp_deploy
- name: Create configlets on local system
  connection: local
  template:
    src: roles/cvp_generate/templates/configlet.j2
    dest: roles/cvp_deploy/vars/main.yml

- name: "Gather CVP facts {{ inventory_hostname }}"
  arista.cvp.cv_facts:
    facts:
      configlets
  register: CVP_FACTS

- name: "Configure configlet on {{inventory_hostname}}"
  # include_vars: "roles/cvp_deploy/files/"
  arista.cvp.cv_configlet:
    cvp_facts: "{{ CVP_FACTS.ansible_facts }}"
    configlets: "{{ CVP_CONFIGLETS }}"
    configlet_filter: ["ANSIBLE_OVERLAY"]
    state: present
  register: CVP_CONFIGLET_RESULT

# - name: 'Display cv_configlet result'
#   debug:
#     msg: '{{ CVP_CONFIGLET_RESULT }}'

- name: "Gather CVP facts {{inventory_hostname}}"
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: "Configure devices on {{inventory_hostname}}"
  arista.cvp.cv_device:
    devices: "{{ CVP_DEVICES }}"
    cvp_facts: '{{ CVP_FACTS.ansible_facts }}'
    device_filter: ['LEAF1A', 'LEAF1B', 'LEAF2A', 'LEAF2B']
    configlet_mode: merge
  register: CVP_DEVICES_RESULTS

- name: 'Display pending tasks from {{inventory_hostname}}'
  debug:
    msg: '{{CVP_DEVICES_RESULTS.data.tasks}}'

- name: "Gather CVP facts from {{inventory_hostname}}"
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: 'Execute all pending tasks and wait for completion for 90 seconds'
  arista.cvp.cv_task:
    tasks: "{{CVP_FACTS.ansible_facts.tasks}}"
    wait: 300