---
# tasks file for eos_generate
- name: Generate configlet configuration
  connection: local
  template:
    src: overlay_config.j2
    dest: roles/cvp_generate/files/{{ inventory_hostname }}_overlay